Complete Code Pull Request
DarkxDev/Capstone-1 pull request #1
Opened 2022-12-27 17:21 UTC by DarkxDev

- Added the full code for the HTML/CSS & JavaScript Microverse Project - Conference Page

2023-01-04 18:25 UTC, OLIPLICHE requested changes
Hi @DarkxDev, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linter is green (the last commit have a green check mark (✅)) 👏
- Commit messages are meaningful 👏 👏
- GitHub flow 👏 👏

## Required Changes ♻️
- Please recorded a video presenting the features of the project as stated in the requirements. And make visible the video Link in your readme if possible.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 18:25 UTC, OLIPLICHE commented on about.html
> +  </section>
- Please this section contains a header, a divider, a paragraph of text, and an image or large logo.
- See your design 
- 
![Capture](https://user-images.githubusercontent.com/63972670/210620817-c723ec53-5020-468c-926e-031500955ea6.PNG)
- 
- Original design
![Capture1](https://user-images.githubusercontent.com/63972670/210620992-9f668624-a5bc-43cb-9580-253751600561.PNG)

2023-01-04 18:25 UTC, OLIPLICHE commented on about.html
> +  </section>
- Make this section looks like the original design: A centered column that includes a section header, a divider, a line of text, and two images with text centered over them, Also change the color of the pictures
- Your design: 
![Capture](https://user-images.githubusercontent.com/63972670/210621704-3020c973-bc10-4b2d-a377-5766542b27ba.PNG)
- Original Des.
- 
![Capture1](https://user-images.githubusercontent.com/63972670/210621802-60e4d3cf-52e4-40d5-b299-53934c9f61a1.PNG)

2023-01-04 18:25 UTC, OLIPLICHE commented on index.html
> +      <h1>Main Program</h1>
- Please no more than 1, `h1` tag on each page. Kindly fix that because  `h1` defines the most important heading

2023-01-04 18:25 UTC, OLIPLICHE commented on about.html
> +      <h1 class="title">PIXEL 7 PHONES ARE HERE</h1>
- Please no more than 1, `h1` tag on each page. Kindly fix that because `h1` defines the most important heading.

2023-01-04 20:18 UTC, DarkxDev commented on about.html
> +    </div>
@OLIPLICHE Please explain what you mean by:
"make sure the logo in the footer must be the same logo at the top bar of the page. not different logo."

Are you referring to the "Google" logo I used in the navbar? Do you want me to use that same logo for the footer instead of the "Creative Commons" one?

2023-01-04 20:50 UTC, DarkxDev commented on about.html
> +  </section>
@OLIPLICHE referring to this sentence: 
"Also change the color of the pictures"

Graphics Design is not part of the program or is relevant to building a website as a Web Developer. Also, I am using different images as placeholders to personalize the content of the page since I am using a fictional custom topic as requested by the capstone.

Please provide the images you are requesting to be placed so future code reviewers can have an idea of why are those images there.

2023-01-04 21:49 UTC, DarkxDev commented on about.html
> +    </div>
Since I get no answer from you, I will keep different logos on the top bar and footer, since the first one is for the topic of the website, and the second one is for the nature of the project. This is the way intended in the design and following this specific instruction would go against it.

The other changes have been implemented without any issues, thank you.

2023-01-04 21:51 UTC, DarkxDev commented on about.html
> +  </section>
Since I get no answer from you, I will keep these images given that they do not go against the design, and rather work as placeholder images for customizing the content of the website and its topic. Consider it like any other text I change for the required purpose of customization as stated in the capstone instructions.

Other changes have been implemented without any issues, thank you.

2023-01-04 22:39 UTC, jerryowusu commented on about.html
> +  </section>
Well done for making most of the changes requested by the previous reviewer, however, there is one more changes to go. As stated by the previous reviewer, kindly make this section look like the original design. The only difference now is to add the centered text over the images with the blurred color as shown below. :point_down: 
You can achieve this by using a mix-blend-mode and/or z-index :wink: 

### Your design

![Screenshot from 2023-01-04 22-33-22](https://user-images.githubusercontent.com/65233860/210662814-1979b606-d7e8-45db-91c1-47818db637ff.png)



### The original design

![Screenshot from 2023-01-04 22-33-41](https://user-images.githubusercontent.com/65233860/210662831-34cc7174-8d50-4024-810c-fe0576707e17.png)

2023-01-04 22:39 UTC, jerryowusu commented on about.html
> +  </section>
> @OLIPLICHE referring to this sentence: "Also change the color of the pictures"
> 
> Graphics Design is not part of the program or is relevant to building a website as a Web Developer. Also, I am using different images as placeholders to personalize the content of the page since I am using a fictional custom topic as requested by the capstone.
> 
> Please provide the images you are requesting to be placed so future code reviewers can have an idea of why are those images there.

@DarkxDev this is not done by graphic design. You can use HTML and CSS to achieve the same effect. It contains an image with a white text + plus a blurred orange background over it.

2023-01-04 22:50 UTC, jerryowusu requested changes
Hi @DarkxDev , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost there](https://user-images.githubusercontent.com/65233860/210664823-23c50829-2418-4663-91a8-a24b1b6d7857.jpg)


 ## Highlights
All linters are passing :heavy_check_mark: 
Great design :heavy_check_mark: 
Nice and clean code :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 22:50 UTC, jerryowusu commented on index.html
> +  </section>
- [ ] [Optional] Kindly note that the mobile version of the homepage does not have the footer (partners and logo) but ends at the more button. Kindly check and update it accordingly :wink:

2023-01-04 22:56 UTC, jerryowusu requested changes
Hi @DarkxDev , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost there](https://user-images.githubusercontent.com/65233860/210664823-23c50829-2418-4663-91a8-a24b1b6d7857.jpg)


 ## Highlights
All linters are passing :heavy_check_mark: 
Great design :heavy_check_mark: 
Nice and clean code :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 22:56 UTC, jerryowusu commented on about.html
> +  </section>
Well done for making most of the changes requested by the previous reviewer, however, there is one more changes to go. As stated by the previous reviewer, kindly make this section look like the original design. The only difference now is to add the centered text over the images with the blurred color as shown below. :point_down: 
You can achieve this by using a mix-blend-mode and/or z-index :wink: 

### Your design

![Screenshot from 2023-01-04 22-33-22](https://user-images.githubusercontent.com/65233860/210662814-1979b606-d7e8-45db-91c1-47818db637ff.png)



### The original design

![Screenshot from 2023-01-04 22-33-41](https://user-images.githubusercontent.com/65233860/210662831-34cc7174-8d50-4024-810c-fe0576707e17.png)

2023-01-04 22:56 UTC, jerryowusu commented on index.html
> +  </section>
- [ ] [Optional] Kindly note that the mobile version of the homepage does not have the footer (partners and logo) but ends at the more button. Kindly check and update it accordingly :wink:

2023-01-04 23:59 UTC, Owusu-Desmond requested changes
Hi @DarkxDev  :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 23:59 UTC, Owusu-Desmond commented on about.html
> +      </ul>
- [ ] Please note that one of the main objectives of this project is the ability to create UIs using a preferred design and from the project requirement as requested by the previous reviewers your need to follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) including **Colors** but comparing the two design, the color does not look the same so I think is better if you just the color to match the preferred design.
### Your Design 
![Screenshot from 2023-01-04 23-56-26](https://user-images.githubusercontent.com/92303891/210671997-e0f9bc14-94c7-49cb-a16e-113933d03692.png)
### Prefered design
![image](https://user-images.githubusercontent.com/92303891/210672083-93afdd9d-633a-45fb-917b-cf50be199c56.png)

2023-01-05 00:34 UTC, Reem-lab approved these changes
# Hi @DarkxDev, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights ✨✨
- No Linters errors ✅ 
- Followed GitHubflow ✅
- Great working on the functionality🔥🚀🎉
- Professional README 🔥🚀💯
- Great working on the design ✅
- Great working on the deployment and the presentation video ✅✅



## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 00:34 UTC, Reem-lab commented on index.html
> +  </section>
- [ OPTIONAL ] In your home page for mobile version I can see the footers but in the given design there is no footer for the mobile version so kindly remove both partners and last footer from your home page just in the mobile version. ✅✨🙏🏻

- Your design
![image](https://user-images.githubusercontent.com/58553711/210675464-c2e4a220-123e-43cf-b2f0-c8a179977518.png)


- Given
![image](https://user-images.githubusercontent.com/58553711/210465302-00c881df-11b9-4482-9ed4-7a3711343869.png)

2023-01-05 00:36 UTC, merged

2023-01-05 08:34 UTC, OLIPLICHE commented on about.html
> +    </div>
> Since I get no answer from you, I will keep different logos on the top bar and footer, since the first one is for the topic of the website, and the second one is for the nature of the project. This is the way intended in the design and following this specific instruction would go against it.
> 
> The other changes have been implemented without any issues, thank you.

@DarkxDev I was off and did not see your notification. sorry about that. I gave the Link to the original design, it is pasted under the required change section in the sum-up of the review, you could have looked at it if you did not understand. Moreover, You are also learning How to work on clients' needs or requests on a project therefore you have to try to build the design requested with colors included etc ...
All the best, Happy coding 👍